name: "gpt-neox-065b-native"
rubik_job {
  fsdp {
    sharding_strategy: FULL_SHARD
    sharded_data_parallel_degree: 0
  }
  model {
    transformer_model {
      named_model: GPT_NEOX_065B
    }
  }
}
runtime {
  nodes {
    num_nodes: 16
  }
}
