name: "gpt-neox-065b"
rubik_job {
  fsdp {
    sharding_strategy: HYBRID_SHARD
    sharded_data_parallel_degree: 256
  }
  model {
    transformer_model {
      named_model: GPT_NEOX_065B
    }
  }
}
runtime {
  nodes {
    num_nodes: 32
  }
}
