name: "llama2-007b-native"
rubik_job {
  fsdp {
    sharding_strategy: FULL_SHARD
    sharded_data_parallel_degree: 0
  }
  model {
    transformer_model {
      named_model: LLAMA_V2_007B
    }
  }
}
runtime {
  nodes {
    num_nodes: 1
  }
}
